-- Generated by scripts/bundle.lua. Do not edit manually.
-- Run `make bundle` from the tourguide.nvim repository root to update.

if vim.g.loaded_tourguide_nvim == 1 then
  return
end

package.preload["tourguide.state"] = function()
local M = {}

M.ns = vim.api.nvim_create_namespace("tourguide")
M.tour = nil
M.steps = {}
M.index = 0
M.sidebar = { buf = nil, win = nil, width = 34 }
M.windows = {}
M.options = { prompt_keymaps = true }

function M.reset()
  M.tour = nil
  M.steps = {}
  M.index = 0
  M.windows = {}
  if M.sidebar.win and vim.api.nvim_win_is_valid(M.sidebar.win) then
    pcall(vim.api.nvim_win_close, M.sidebar.win, true)
  end
  M.sidebar = { buf = nil, win = nil, width = M.sidebar.width or 34 }
end

function M.current_step()
  return M.steps[M.index]
end

return M

end

package.preload["tourguide.resolve"] = function()
local M = {}

local function line_count(buf)
  return vim.api.nvim_buf_line_count(buf)
end

function M.section(buf, section)
  if section.range then
    return section.range[1], section.range[2] or section.range[1]
  end

  local needle = section.search or section.symbol
  if needle then
    local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
    for i, line in ipairs(lines) do
      if line:find(needle, 1, true) then
        local extra = section.context or 8
        return i, math.min(line_count(buf), i + extra)
      end
    end
  end

  return 1, math.min(line_count(buf), 1)
end

return M

end

package.preload["tourguide.annotations"] = function()
local state = require("tourguide.state")
local resolve = require("tourguide.resolve")

local M = {}

local function define_highlights()
  vim.api.nvim_set_hl(0, "TourGuidePrefix", { link = "DiagnosticInfo", default = true })
  vim.api.nvim_set_hl(0, "TourGuideNote", { link = "Comment", default = true })
  vim.api.nvim_set_hl(0, "TourGuideFlowSection", { link = "Search", default = true })
end

local function clamp_line(buf, line)
  local count = vim.api.nvim_buf_line_count(buf)
  return math.max(0, math.min(count - 1, line - 1))
end

function M.clear(buf)
  if buf and vim.api.nvim_buf_is_valid(buf) then
    vim.api.nvim_buf_clear_namespace(buf, state.ns, 0, -1)
  end
end

function M.apply(buf, sections)
  define_highlights()
  M.clear(buf)
  local first = nil

  for _, section in ipairs(sections or {}) do
    local start_line, end_line = resolve.section(buf, section)
    first = first or start_line

    for line = start_line, end_line do
      vim.api.nvim_buf_set_extmark(buf, state.ns, clamp_line(buf, line), 0, {
        line_hl_group = section.hl or "Visual"
      })
    end

    if section.note then
      local placement = section.placement or "above"
      local target = placement == "below" and end_line or start_line
      local opts
      if placement == "eol" or placement == "inline" then
        opts = {
          virt_text = {
            { "  >> TourGuide", "TourGuidePrefix" },
            { ": " .. section.note, "TourGuideNote" }
          },
          virt_text_pos = "eol"
        }
      else
        opts = {
          virt_lines = {
            {
              { ">> TourGuide", "TourGuidePrefix" },
              { ": " .. section.note, "TourGuideNote" }
            }
          },
          virt_lines_above = placement ~= "below"
        }
      end
      vim.api.nvim_buf_set_extmark(buf, state.ns, clamp_line(buf, target), 0, opts)
    end
  end

  return first
end

return M

end

package.preload["tourguide.sidebar"] = function()
local state = require("tourguide.state")

local M = {}

local function define_highlights()
  vim.api.nvim_set_hl(0, "TourGuideTitle", { link = "Title", default = true })
  vim.api.nvim_set_hl(0, "TourGuideTopic", { link = "Directory", default = true })
  vim.api.nvim_set_hl(0, "TourGuideActive", { link = "Visual", default = true })
  vim.api.nvim_set_hl(0, "TourGuideFile", { link = "Comment", default = true })
end

local function ensure_sidebar()
  if
    state.sidebar.win
    and vim.api.nvim_win_is_valid(state.sidebar.win)
    and state.sidebar.buf
    and vim.api.nvim_buf_is_valid(state.sidebar.buf)
    and vim.api.nvim_win_get_buf(state.sidebar.win) == state.sidebar.buf
  then
    return state.sidebar.buf, state.sidebar.win
  end

  state.sidebar = { buf = nil, win = nil, width = state.sidebar.width or 34 }
  local previous = vim.api.nvim_get_current_win()
  vim.cmd("topleft vertical " .. tostring(state.sidebar.width or 34) .. "new")
  local win = vim.api.nvim_get_current_win()
  local buf = vim.api.nvim_get_current_buf()
  vim.bo[buf].buftype = "nofile"
  vim.bo[buf].bufhidden = "wipe"
  vim.bo[buf].swapfile = false
  vim.bo[buf].modifiable = false
  vim.wo[win].number = false
  vim.wo[win].relativenumber = false
  vim.wo[win].wrap = false
  vim.wo[win].winfixwidth = true
  vim.api.nvim_win_set_width(win, state.sidebar.width or 34)
  vim.api.nvim_buf_set_name(buf, "TourGuide")
  state.sidebar = { buf = buf, win = win, width = state.sidebar.width or 34 }
  if previous and vim.api.nvim_win_is_valid(previous) then vim.api.nvim_set_current_win(previous) end
  return buf, win
end

function M.render()
  if not state.tour then return end
  define_highlights()
  local buf = ensure_sidebar()
  local win = state.sidebar.win
  local lines = { state.tour.title or "TourGuide", string.rep("=", 24), "" }
  local hls = {
    { group = "TourGuideTitle", line = 0, start_col = 0, end_col = -1 },
    { group = "TourGuideTitle", line = 1, start_col = 0, end_col = -1 }
  }

  local last_topic = nil
  for i, step in ipairs(state.steps) do
    local topic = step._breadcrumbs[1]
    if topic ~= last_topic then
      local line = #lines
      table.insert(lines, topic)
      table.insert(hls, { group = "TourGuideTopic", line = line, start_col = 0, end_col = -1 })
      last_topic = topic
    end
    local active = i == state.index and ">" or " "
    local label = step._label
    if step._display_file then label = label .. "  [" .. step._display_file .. "]" end
    local line = #lines
    table.insert(lines, string.format("%s %02d. %s", active, i, label))
    if i == state.index then
      table.insert(hls, { group = "TourGuideActive", line = line, start_col = 0, end_col = -1 })
    elseif step._display_file then
      local start_col = lines[#lines]:find("%[")
      if start_col then
        table.insert(hls, { group = "TourGuideFile", line = line, start_col = start_col - 1, end_col = -1 })
      end
    end
  end

  vim.bo[buf].modifiable = true
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
  vim.bo[buf].modifiable = false
  vim.api.nvim_buf_clear_namespace(buf, state.ns, 0, -1)
  for _, hl in ipairs(hls) do
    vim.api.nvim_buf_add_highlight(buf, state.ns, hl.group, hl.line, hl.start_col, hl.end_col)
  end
  if win and vim.api.nvim_win_is_valid(win) then
    vim.wo[win].winfixwidth = true
    vim.api.nvim_win_set_width(win, state.sidebar.width or 34)
  end
end

return M

end

package.preload["tourguide.layout"] = function()
local annotations = require("tourguide.annotations")
local state = require("tourguide.state")

local M = {}

local function enforce_sidebar_width()
  if state.sidebar.win and vim.api.nvim_win_is_valid(state.sidebar.win) then
    vim.wo[state.sidebar.win].winfixwidth = true
    pcall(vim.api.nvim_win_set_width, state.sidebar.win, state.sidebar.width or 34)
  end
end

local function find_content_window(exclude)
  for _, win in ipairs(vim.api.nvim_list_wins()) do
    if win ~= state.sidebar.win and win ~= exclude then return win end
  end
end

local function ensure_content_window()
  local current = vim.api.nvim_get_current_win()
  if current ~= state.sidebar.win then return current end
  local target = find_content_window()
  if target then
    vim.api.nvim_set_current_win(target)
    return target
  end
  vim.cmd("rightbelow vnew")
  enforce_sidebar_width()
  return vim.api.nvim_get_current_win()
end

local function full_path(root, file)
  if file:sub(1, 1) == "/" then return file end
  return root:gsub("/$", "") .. "/" .. file
end

local function open_file(root, file)
  ensure_content_window()
  vim.cmd("edit " .. vim.fn.fnameescape(full_path(root, file)))
  enforce_sidebar_width()
  return vim.api.nvim_get_current_buf(), vim.api.nvim_get_current_win()
end

local function with_flow_numbers(sections, start_index)
  if not start_index then return sections, start_index end
  local numbered = {}
  local n = start_index
  for _, section in ipairs(sections or {}) do
    local copy = vim.deepcopy(section)
    copy.note = string.format("[%02d] ", n) .. (copy.note or "")
    copy.hl = copy.hl or "TourGuideFlowSection"
    table.insert(numbered, copy)
    n = n + 1
  end
  return numbered, n
end

local function render_file(root, file, sections)
  local buf, win = open_file(root, file)
  local first = annotations.apply(buf, sections)
  if first then
    vim.api.nvim_win_set_cursor(win, { first, 0 })
    vim.cmd("normal! zz")
  end
  return buf, win
end

local function render_markdown(step)
  ensure_content_window()
  vim.cmd("enew")
  enforce_sidebar_width()
  local buf = vim.api.nvim_get_current_buf()
  vim.bo[buf].buftype = "nofile"
  vim.bo[buf].bufhidden = "wipe"
  vim.bo[buf].swapfile = false
  vim.bo[buf].filetype = "markdown"
  vim.api.nvim_buf_set_name(buf, "TourGuide: " .. (step.title or "Notes"))
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.split(step.markdown or "", "\n", { plain = true }))
  vim.bo[buf].modifiable = false
  return buf, vim.api.nvim_get_current_win()
end

local function close_extra_windows(windows, keep)
  for _, win in ipairs(windows or {}) do
    if vim.api.nvim_win_is_valid(win) and win ~= state.sidebar.win and win ~= keep and #vim.api.nvim_list_wins() > 1 then
      if vim.api.nvim_get_current_win() == win then
        local candidate = find_content_window(win) or state.sidebar.win
        if candidate and vim.api.nvim_win_is_valid(candidate) then vim.api.nvim_set_current_win(candidate) end
      end
      pcall(vim.api.nvim_win_close, win, true)
      enforce_sidebar_width()
    end
  end
end

function M.render(step, tour, previous_windows)
  local equalalways = vim.o.equalalways
  vim.o.equalalways = false
  local target = ensure_content_window()
  close_extra_windows(previous_windows, target)
  vim.api.nvim_set_current_win(target)
  local root = tour.root or vim.fn.getcwd()
  local windows = {}

  if step.markdown then
    local _, win = render_markdown(step)
    table.insert(windows, win)
  elseif step.panes then
    local layout = step.layout or "vertical"
    local flow_index = step.flow == false and nil or 1
    for i, pane in ipairs(step.panes) do
      if i > 1 then
        vim.cmd(layout == "horizontal" and "split" or "vsplit")
        enforce_sidebar_width()
      end
      local sections = pane.sections
      if flow_index then sections, flow_index = with_flow_numbers(pane.sections, flow_index) end
      local _, win = render_file(root, pane.file, sections)
      table.insert(windows, win)
    end
  elseif step.file then
    local _, win = render_file(root, step.file, step.sections)
    table.insert(windows, win)
  end

  enforce_sidebar_width()
  vim.o.equalalways = equalalways
  return windows
end

return M

end

package.preload["tourguide.navigation"] = function()
local state = require("tourguide.state")
local sidebar = require("tourguide.sidebar")
local layout = require("tourguide.layout")

local M = {}

function M.jump(index)
  if not state.tour then
    vim.notify("No active TourGuide", vim.log.levels.WARN)
    return
  end
  if index < 1 or index > #state.steps then
    vim.notify("End of TourGuide", vim.log.levels.INFO)
    return
  end
  state.index = index
  sidebar.render()
  state.windows = layout.render(state.current_step(), state.tour, state.windows)
end

function M.next() M.jump(state.index + 1) end
function M.prev() M.jump(state.index - 1) end

local function topic_at(index)
  local step = state.steps[index]
  return step and step._breadcrumbs and step._breadcrumbs[1] or nil
end

function M.next_topic()
  local current_topic = topic_at(state.index)
  for index = state.index + 1, #state.steps do
    if topic_at(index) ~= current_topic then
      M.jump(index)
      return
    end
  end
  vim.notify("End of TourGuide", vim.log.levels.INFO)
end

function M.prev_topic()
  local current_topic = topic_at(state.index)
  local previous_topic_index = nil

  for index = state.index - 1, 1, -1 do
    if topic_at(index) ~= current_topic then
      previous_topic_index = index
      break
    end
  end

  if not previous_topic_index then
    vim.notify("End of TourGuide", vim.log.levels.INFO)
    return
  end

  local previous_topic = topic_at(previous_topic_index)
  while previous_topic_index > 1 and topic_at(previous_topic_index - 1) == previous_topic do
    previous_topic_index = previous_topic_index - 1
  end
  M.jump(previous_topic_index)
end

return M

end

package.preload["tourguide.keymaps"] = function()
local state = require("tourguide.state")

local M = {}

local actions = {
  { key = "next_section", prompt = "TourGuide next section keymap (empty to skip):", command = "<Cmd>TourGuideNext<CR>" },
  { key = "prev_section", prompt = "TourGuide previous section keymap (empty to skip):", command = "<Cmd>TourGuidePrev<CR>" },
  { key = "next_topic", prompt = "TourGuide next topic keymap (empty to skip):", command = "<Cmd>TourGuideNextTopic<CR>" },
  { key = "prev_topic", prompt = "TourGuide previous topic keymap (empty to skip):", command = "<Cmd>TourGuidePrevTopic<CR>" },
}

local active = {}

local function config_path()
  return vim.fn.stdpath("state") .. "/tourguide/keymaps.json"
end

local function read_preferences()
  local path = config_path()
  if vim.fn.filereadable(path) == 0 then return nil end

  local ok, decoded = pcall(vim.fn.json_decode, table.concat(vim.fn.readfile(path), "\n"))
  if ok and type(decoded) == "table" then return decoded end
  vim.notify("TourGuide could not read keymap preferences", vim.log.levels.WARN)
  return nil
end

local function write_preferences(preferences)
  local path = config_path()
  vim.fn.mkdir(vim.fn.fnamemodify(path, ":h"), "p")
  vim.fn.writefile(vim.split(vim.fn.json_encode(preferences), "\n", { plain = true }), path)
end

local function prompt_preferences(done)
  local preferences = {}
  local index = 1

  local function prompt_next()
    local action = actions[index]
    if not action then
      write_preferences(preferences)
      done(preferences)
      return
    end

    vim.ui.input({ prompt = action.prompt }, function(value)
      preferences[action.key] = value or ""
      index = index + 1
      prompt_next()
    end)
  end

  prompt_next()
end

local function restore_map(lhs, previous)
  pcall(vim.keymap.del, "n", lhs)
  if previous and previous.lhs and previous.lhs ~= "" then
    pcall(vim.fn.mapset, "n", false, previous)
  end
end

function M.restore()
  for _, mapping in ipairs(active) do
    restore_map(mapping.lhs, mapping.previous)
  end
  active = {}
end

local function apply_preferences(preferences)
  M.restore()

  for _, action in ipairs(actions) do
      local lhs = preferences[action.key]
    if type(lhs) == "string" and lhs ~= "" then
      local previous = vim.fn.maparg(lhs, "n", false, true)
      if not previous or not previous.lhs or previous.lhs == "" then previous = nil end
      table.insert(active, { lhs = lhs, previous = previous })
      vim.keymap.set("n", lhs, action.command, { silent = true, desc = "TourGuide " .. action.key:gsub("_", " ") })
    end
  end
end

function M.activate()
  if not state.options.prompt_keymaps or #vim.api.nvim_list_uis() == 0 then
    M.restore()
    return
  end

  local preferences = read_preferences()
  if preferences then
    apply_preferences(preferences)
    return
  end

  prompt_preferences(apply_preferences)
end

return M

end

package.preload["tourguide.loader"] = function()
local M = {}

local function basename(path)
  return path:match("([^/]+)$") or path
end

local function is_step(node)
  return node.file or node.markdown or node.panes
end

local function flatten_node(node, breadcrumbs, out, depth)
  local next_breadcrumbs = vim.deepcopy(breadcrumbs)
  table.insert(next_breadcrumbs, node.title or "Untitled")

  if is_step(node) then
    node._breadcrumbs = next_breadcrumbs
    node._depth = depth
    node._label = node.title or node.file or "Untitled"
    node._kind = node.markdown and "markdown" or node.panes and "split" or "file"
    node._display_file = node.file and basename(node.file) or nil
    table.insert(out, node)
  end

  for _, child in ipairs(node.children or {}) do
    flatten_node(child, next_breadcrumbs, out, depth + 1)
  end
end

function M.flatten(tour)
  local out = {}
  for _, topic in ipairs(tour.topics or {}) do
    flatten_node(topic, {}, out, 0)
  end
  return out
end

function M.load(path_or_module)
  local ok, tour
  if path_or_module:match("%.lua$") or path_or_module:match("/") then
    ok, tour = pcall(dofile, path_or_module)
  else
    ok, tour = pcall(require, path_or_module)
  end
  if not ok then error(tour) end
  if type(tour) ~= "table" then error("tour must return a table") end
  if not tour.root then tour.root = vim.fn.getcwd() end
  local steps = M.flatten(tour)
  if #steps == 0 then error("tour has no steps") end
  return tour, steps
end

return M

end

package.preload["tourguide"] = function()
local loader = require("tourguide.loader")
local state = require("tourguide.state")
local nav = require("tourguide.navigation")
local sidebar = require("tourguide.sidebar")
local keymaps = require("tourguide.keymaps")

local M = {}

function M.start(path_or_module)
  local tour, steps = loader.load(path_or_module)
  keymaps.restore()
  state.reset()
  state.tour = tour
  state.steps = steps
  state.index = 1
  sidebar.render()
  state.windows = require("tourguide.layout").render(state.current_step(), state.tour, {})
  keymaps.activate()
end

function M.next() nav.next() end
function M.prev() nav.prev() end
function M.next_topic() nav.next_topic() end
function M.prev_topic() nav.prev_topic() end
function M.jump(index) nav.jump(index) end

function M.close()
  keymaps.restore()
  for _, step in ipairs(state.steps) do
    if step.file and state.tour then
      local path = (state.tour.root or vim.fn.getcwd()):gsub("/$", "") .. "/" .. step.file
      local buf = vim.fn.bufnr(path)
      if buf ~= -1 then vim.api.nvim_buf_clear_namespace(buf, state.ns, 0, -1) end
    end
  end
  state.reset()
end

function M.setup(opts)
  opts = opts or {}
  if opts.sidebar_width then state.sidebar.width = opts.sidebar_width end
  if opts.prompt_keymaps ~= nil then state.options.prompt_keymaps = opts.prompt_keymaps end

  vim.api.nvim_create_user_command("TourGuide", function(cmd) M.start(cmd.args) end, { nargs = 1, complete = "file" })
  vim.api.nvim_create_user_command("TourGuideNext", M.next, {})
  vim.api.nvim_create_user_command("TourGuidePrev", M.prev, {})
  vim.api.nvim_create_user_command("TourGuideNextTopic", M.next_topic, {})
  vim.api.nvim_create_user_command("TourGuidePrevTopic", M.prev_topic, {})
  vim.api.nvim_create_user_command("TourGuideJump", function(cmd) M.jump(tonumber(cmd.args)) end, { nargs = 1 })
  vim.api.nvim_create_user_command("TourGuideClose", M.close, {})
end

return M

end

vim.g.loaded_tourguide_nvim = 1
require("tourguide").setup()
