-- Generated by scripts/bundle.lua. Do not edit manually.
-- Run `make bundle` from the tourguide.nvim repository root to update.

if vim.g.loaded_tourguide_nvim == 1 then
  return
end

package.preload["tourguide.state"] = function()
local M = {}

M.ns = vim.api.nvim_create_namespace("tourguide")
M.tour = nil
M.steps = {}
M.index = 0
M.sidebar = { buf = nil, win = nil, width = 34 }
M.windows = {}
M.options = { prompt_keymaps = true }

function M.reset()
  M.tour = nil
  M.steps = {}
  M.index = 0
  M.windows = {}
  if M.sidebar.win and vim.api.nvim_win_is_valid(M.sidebar.win) then
    pcall(vim.api.nvim_win_close, M.sidebar.win, true)
  end
  M.sidebar = { buf = nil, win = nil, width = M.sidebar.width or 34 }
end

function M.current_step()
  return M.steps[M.index]
end

return M

end

package.preload["tourguide.resolve"] = function()
local M = {}

local function line_count(buf)
  return vim.api.nvim_buf_line_count(buf)
end

function M.section(buf, section)
  if section.range then
    return section.range[1], section.range[2] or section.range[1]
  end

  local needle = section.search or section.symbol
  if needle then
    local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
    for i, line in ipairs(lines) do
      if line:find(needle, 1, true) then
        local extra = section.context or 8
        return i, math.min(line_count(buf), i + extra)
      end
    end
  end

  return 1, math.min(line_count(buf), 1)
end

return M

end

package.preload["tourguide.annotations"] = function()
local state = require("tourguide.state")
local resolve = require("tourguide.resolve")

local M = {}
local dim_cache = {}
local apply_version = 0

local function blend_channel(fg, bg, alpha)
  return math.floor((fg * alpha) + (bg * (1 - alpha)) + 0.5)
end

local function blend_color(fg, bg, alpha)
  local r = blend_channel(math.floor(fg / 0x10000) % 0x100, math.floor(bg / 0x10000) % 0x100, alpha)
  local g = blend_channel(math.floor(fg / 0x100) % 0x100, math.floor(bg / 0x100) % 0x100, alpha)
  local b = blend_channel(fg % 0x100, bg % 0x100, alpha)
  return string.format("#%02x%02x%02x", r, g, b)
end

local function define_highlights()
  local normal = vim.api.nvim_get_hl(0, { name = "Normal", link = false })
  local info = vim.api.nvim_get_hl(0, { name = "DiagnosticInfo", link = false })
  local search = vim.api.nvim_get_hl(0, { name = "Search", link = false })
  local fg = blend_color(normal.fg or 0xffffff, normal.bg or 0x000000, 0.45)
  local accent = search.fg or info.fg or normal.fg or 0xffffff
  local bg = search.bg or blend_color(info.fg or normal.fg or 0xffffff, normal.bg or 0x000000, 0.22)

  vim.api.nvim_set_hl(0, "TourGuidePrefix", { link = "DiagnosticInfo", default = true })
  vim.api.nvim_set_hl(0, "TourGuideNote", { link = "Comment", default = true })
  vim.api.nvim_set_hl(0, "TourGuideCallout", { bg = bg, default = true })
  vim.api.nvim_set_hl(0, "TourGuideCalloutLabel", { fg = accent, bg = bg, bold = true, default = true })
  vim.api.nvim_set_hl(0, "TourGuideCalloutText", { fg = normal.fg, bg = bg, default = true })
  vim.api.nvim_set_hl(0, "TourGuideSectionSign", { fg = accent, bold = true, default = true })
  vim.api.nvim_set_hl(0, "TourGuideDim", { fg = fg, default = true })
end

local function wrap_text(text, width)
  local lines = {}
  local current = ""

  for word in tostring(text):gmatch("%S+") do
    if current == "" then
      current = word
    elseif #current + #word + 1 <= width then
      current = current .. " " .. word
    else
      table.insert(lines, current)
      current = word
    end
  end

  if current ~= "" then table.insert(lines, current) end
  if #lines == 0 then table.insert(lines, "") end
  return lines
end

local function callout_width(buf)
  for _, win in ipairs(vim.api.nvim_list_wins()) do
    if vim.api.nvim_win_get_buf(win) == buf then
      return math.max(32, vim.api.nvim_win_get_width(win) - 8)
    end
  end
  return 72
end

local function note_lines(note, width)
  local lines = {}
  local prefix_width = vim.fn.strdisplaywidth("💬 ")
  local text_width = math.max(20, width - prefix_width)

  for index, text in ipairs(wrap_text(note, text_width)) do
    local prefix = index == 1 and "💬 " or string.rep(" ", prefix_width)
    local used = vim.fn.strdisplaywidth(prefix) + vim.fn.strdisplaywidth(text)
    table.insert(lines, {
      { prefix, "TourGuideCalloutLabel" },
      { text, "TourGuideCalloutText" },
      { string.rep(" ", math.max(0, width - used)), "TourGuideCallout" },
    })
  end
  return lines
end

local function dim_highlight(hl_name)
  hl_name = hl_name or "Normal"
  if dim_cache[hl_name] then return dim_cache[hl_name] end

  local normal = vim.api.nvim_get_hl(0, { name = "Normal", link = false })
  local ok, hl = pcall(vim.api.nvim_get_hl, 0, { name = hl_name, link = false })
  if not ok or not hl or not hl.fg then hl = normal end

  local group = "TourGuideDim" .. hl_name:gsub("[^%w_]", "_")
  vim.api.nvim_set_hl(0, group, vim.tbl_extend("force", hl, {
    fg = blend_color(hl.fg or normal.fg or 0xffffff, normal.bg or 0x000000, 0.45),
  }))
  dim_cache[hl_name] = group
  return group
end

local function clamp_line(buf, line)
  local count = vim.api.nvim_buf_line_count(buf)
  return math.max(0, math.min(count - 1, line - 1))
end

function M.clear(buf)
  if buf and vim.api.nvim_buf_is_valid(buf) then
    vim.api.nvim_buf_clear_namespace(buf, state.ns, 0, -1)
  end
end

local function captures_at(buf, line, col)
  local ok, captures = pcall(vim.treesitter.get_captures_at_pos, buf, line, col)
  if ok then return captures end
  return {}
end

function M.apply(buf, sections, retry)
  apply_version = apply_version + 1
  local version = apply_version
  define_highlights()
  M.clear(buf)
  dim_cache = {}
  local first = nil
  local highlighted = {}
  local found_syntax = false

  pcall(vim.treesitter.start, buf)

  for _, section in ipairs(sections or {}) do
    local start_line, end_line = resolve.section(buf, section)
    first = first or start_line

    for line = start_line, end_line do
      local row = clamp_line(buf, line)
      highlighted[row] = true
      vim.api.nvim_buf_set_extmark(buf, state.ns, row, 0, {
        sign_hl_group = "TourGuideSectionSign",
        sign_text = "│",
        priority = 300
      })
    end

    if section.note then
      local placement = section.placement or "above"
      local target = placement == "below" and end_line or start_line
      local opts = {
        virt_lines = note_lines(section.note, callout_width(buf)),
        virt_lines_above = placement ~= "below" and placement ~= "eol" and placement ~= "inline"
      }
      vim.api.nvim_buf_set_extmark(buf, state.ns, clamp_line(buf, target), 0, opts)
    end
  end

  if first then
    for line = 0, vim.api.nvim_buf_line_count(buf) - 1 do
      if not highlighted[line] then
        local text = vim.api.nvim_buf_get_lines(buf, line, line + 1, false)[1]
        local start_col = 0
        local current_hl = nil

        for col = 0, #text do
          local captures = col < #text and captures_at(buf, line, col) or {}
          local capture = captures[#captures]
          local hl = capture and ("@" .. capture.capture) or "Normal"
          found_syntax = found_syntax or capture ~= nil

          if current_hl and hl ~= current_hl then
            vim.api.nvim_buf_set_extmark(buf, state.ns, line, start_col, {
              end_col = col,
              hl_group = dim_highlight(current_hl),
              priority = 200
            })
            start_col = col
          end
          current_hl = hl
        end

        if #text == 0 then
          vim.api.nvim_buf_set_extmark(buf, state.ns, line, 0, {
            end_col = 0,
            hl_eol = true,
            hl_group = "TourGuideDim",
            priority = 200
          })
        elseif current_hl then
          vim.api.nvim_buf_set_extmark(buf, state.ns, line, start_col, {
            end_col = #text,
            hl_group = dim_highlight(current_hl),
            priority = 200
          })
        end
      end
    end

    if not retry and not found_syntax then
      vim.defer_fn(function()
        if version == apply_version and vim.api.nvim_buf_is_valid(buf) then
          M.apply(buf, sections, true)
        end
      end, 100)
    end
  end

  return first
end

return M

end

package.preload["tourguide.sidebar"] = function()
local state = require("tourguide.state")

local M = {}

local function define_highlights()
  vim.api.nvim_set_hl(0, "TourGuideTitle", { link = "Title", default = true })
  vim.api.nvim_set_hl(0, "TourGuideTopic", { link = "Directory", default = true })
  vim.api.nvim_set_hl(0, "TourGuideActive", { link = "Visual", default = true })
  vim.api.nvim_set_hl(0, "TourGuideFile", { link = "Comment", default = true })
end

local function ensure_sidebar()
  if
    state.sidebar.win
    and vim.api.nvim_win_is_valid(state.sidebar.win)
    and state.sidebar.buf
    and vim.api.nvim_buf_is_valid(state.sidebar.buf)
    and vim.api.nvim_win_get_buf(state.sidebar.win) == state.sidebar.buf
  then
    return state.sidebar.buf, state.sidebar.win
  end

  state.sidebar = { buf = nil, win = nil, width = state.sidebar.width or 34 }
  local previous = vim.api.nvim_get_current_win()
  vim.cmd("topleft vertical " .. tostring(state.sidebar.width or 34) .. "new")
  local win = vim.api.nvim_get_current_win()
  local buf = vim.api.nvim_get_current_buf()
  vim.bo[buf].buftype = "nofile"
  vim.bo[buf].bufhidden = "wipe"
  vim.bo[buf].swapfile = false
  vim.bo[buf].modifiable = false
  vim.wo[win].number = false
  vim.wo[win].relativenumber = false
  vim.wo[win].wrap = false
  vim.wo[win].winfixwidth = true
  vim.api.nvim_win_set_width(win, state.sidebar.width or 34)
  vim.api.nvim_buf_set_name(buf, "TourGuide")
  state.sidebar = { buf = buf, win = win, width = state.sidebar.width or 34 }
  if previous and vim.api.nvim_win_is_valid(previous) then vim.api.nvim_set_current_win(previous) end
  return buf, win
end

function M.render()
  if not state.tour then return end
  define_highlights()
  local buf = ensure_sidebar()
  local win = state.sidebar.win
  local lines = { state.tour.title or "TourGuide", string.rep("=", 24), "" }
  local hls = {
    { group = "TourGuideTitle", line = 0, start_col = 0, end_col = -1 },
    { group = "TourGuideTitle", line = 1, start_col = 0, end_col = -1 }
  }

  local last_topic = nil
  for i, step in ipairs(state.steps) do
    local topic = step._breadcrumbs[1]
    if topic ~= last_topic then
      local line = #lines
      table.insert(lines, topic)
      table.insert(hls, { group = "TourGuideTopic", line = line, start_col = 0, end_col = -1 })
      last_topic = topic
    end
    local active = i == state.index and ">" or " "
    local label = step._label
    if step._display_file then label = label .. "  [" .. step._display_file .. "]" end
    local line = #lines
    table.insert(lines, string.format("%s %02d. %s", active, i, label))
    if i == state.index then
      table.insert(hls, { group = "TourGuideActive", line = line, start_col = 0, end_col = -1 })
    elseif step._display_file then
      local start_col = lines[#lines]:find("%[")
      if start_col then
        table.insert(hls, { group = "TourGuideFile", line = line, start_col = start_col - 1, end_col = -1 })
      end
    end
  end

  vim.bo[buf].modifiable = true
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
  vim.bo[buf].modifiable = false
  vim.api.nvim_buf_clear_namespace(buf, state.ns, 0, -1)
  for _, hl in ipairs(hls) do
    vim.api.nvim_buf_add_highlight(buf, state.ns, hl.group, hl.line, hl.start_col, hl.end_col)
  end
  if win and vim.api.nvim_win_is_valid(win) then
    vim.wo[win].winfixwidth = true
    vim.api.nvim_win_set_width(win, state.sidebar.width or 34)
  end
end

return M

end

package.preload["tourguide.layout"] = function()
local annotations = require("tourguide.annotations")
local state = require("tourguide.state")

local M = {}

local function enforce_sidebar_width()
  if state.sidebar.win and vim.api.nvim_win_is_valid(state.sidebar.win) then
    vim.wo[state.sidebar.win].winfixwidth = true
    pcall(vim.api.nvim_win_set_width, state.sidebar.win, state.sidebar.width or 34)
  end
end

local function find_content_window(exclude)
  for _, win in ipairs(vim.api.nvim_list_wins()) do
    if win ~= state.sidebar.win and win ~= exclude then return win end
  end
end

local function ensure_content_window()
  local current = vim.api.nvim_get_current_win()
  if current ~= state.sidebar.win then return current end
  local target = find_content_window()
  if target then
    vim.api.nvim_set_current_win(target)
    return target
  end
  vim.cmd("rightbelow vnew")
  enforce_sidebar_width()
  return vim.api.nvim_get_current_win()
end

local function full_path(root, file)
  if file:sub(1, 1) == "/" then return file end
  return root:gsub("/$", "") .. "/" .. file
end

local function open_file(root, file)
  ensure_content_window()
  vim.cmd("edit " .. vim.fn.fnameescape(full_path(root, file)))
  enforce_sidebar_width()
  return vim.api.nvim_get_current_buf(), vim.api.nvim_get_current_win()
end

local function with_flow_numbers(sections, start_index)
  if not start_index then return sections, start_index end
  local numbered = {}
  local n = start_index
  for _, section in ipairs(sections or {}) do
    local copy = vim.deepcopy(section)
    copy.note = string.format("[%02d] ", n) .. (copy.note or "")
    table.insert(numbered, copy)
    n = n + 1
  end
  return numbered, n
end

local function render_file(root, file, sections)
  local buf, win = open_file(root, file)
  local first = annotations.apply(buf, sections)
  if first then
    vim.api.nvim_win_set_cursor(win, { first, 0 })
    vim.cmd("normal! zz")
  end
  return buf, win
end

local function render_markdown(step)
  ensure_content_window()
  vim.cmd("enew")
  enforce_sidebar_width()
  local buf = vim.api.nvim_get_current_buf()
  vim.bo[buf].buftype = "nofile"
  vim.bo[buf].bufhidden = "wipe"
  vim.bo[buf].swapfile = false
  vim.bo[buf].filetype = "markdown"
  vim.api.nvim_buf_set_name(buf, "TourGuide: " .. (step.title or "Notes"))
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.split(step.markdown or "", "\n", { plain = true }))
  vim.bo[buf].modifiable = false
  return buf, vim.api.nvim_get_current_win()
end

local function close_extra_windows(windows, keep)
  for _, win in ipairs(windows or {}) do
    if vim.api.nvim_win_is_valid(win) and win ~= state.sidebar.win and win ~= keep and #vim.api.nvim_list_wins() > 1 then
      if vim.api.nvim_get_current_win() == win then
        local candidate = find_content_window(win) or state.sidebar.win
        if candidate and vim.api.nvim_win_is_valid(candidate) then vim.api.nvim_set_current_win(candidate) end
      end
      pcall(vim.api.nvim_win_close, win, true)
      enforce_sidebar_width()
    end
  end
end

function M.render(step, tour, previous_windows)
  local equalalways = vim.o.equalalways
  vim.o.equalalways = false
  local target = ensure_content_window()
  close_extra_windows(previous_windows, target)
  vim.api.nvim_set_current_win(target)
  local root = tour.root or vim.fn.getcwd()
  local windows = {}

  if step.markdown then
    local _, win = render_markdown(step)
    table.insert(windows, win)
  elseif step.panes then
    local layout = step.layout or "vertical"
    local flow_index = step.flow == false and nil or 1
    for i, pane in ipairs(step.panes) do
      if i > 1 then
        vim.cmd(layout == "horizontal" and "split" or "vsplit")
        enforce_sidebar_width()
      end
      local sections = pane.sections
      if flow_index then sections, flow_index = with_flow_numbers(pane.sections, flow_index) end
      local _, win = render_file(root, pane.file, sections)
      table.insert(windows, win)
    end
  elseif step.file then
    local _, win = render_file(root, step.file, step.sections)
    table.insert(windows, win)
  end

  enforce_sidebar_width()
  vim.o.equalalways = equalalways
  return windows
end

return M

end

package.preload["tourguide.navigation"] = function()
local state = require("tourguide.state")
local sidebar = require("tourguide.sidebar")
local layout = require("tourguide.layout")

local M = {}

function M.jump(index)
  if not state.tour then
    vim.notify("No active TourGuide", vim.log.levels.WARN)
    return
  end
  if index < 1 or index > #state.steps then
    vim.notify("End of TourGuide", vim.log.levels.INFO)
    return
  end
  state.index = index
  sidebar.render()
  state.windows = layout.render(state.current_step(), state.tour, state.windows)
end

function M.next() M.jump(state.index + 1) end
function M.prev() M.jump(state.index - 1) end

local function topic_at(index)
  local step = state.steps[index]
  return step and step._breadcrumbs and step._breadcrumbs[1] or nil
end

function M.next_topic()
  local current_topic = topic_at(state.index)
  for index = state.index + 1, #state.steps do
    if topic_at(index) ~= current_topic then
      M.jump(index)
      return
    end
  end
  vim.notify("End of TourGuide", vim.log.levels.INFO)
end

function M.prev_topic()
  local current_topic = topic_at(state.index)
  local previous_topic_index = nil

  for index = state.index - 1, 1, -1 do
    if topic_at(index) ~= current_topic then
      previous_topic_index = index
      break
    end
  end

  if not previous_topic_index then
    vim.notify("End of TourGuide", vim.log.levels.INFO)
    return
  end

  local previous_topic = topic_at(previous_topic_index)
  while previous_topic_index > 1 and topic_at(previous_topic_index - 1) == previous_topic do
    previous_topic_index = previous_topic_index - 1
  end
  M.jump(previous_topic_index)
end

return M

end

package.preload["tourguide.keymaps"] = function()
local state = require("tourguide.state")

local M = {}

local actions = {
  { key = "next_section", prompt = "TourGuide next section keymap (empty to skip):", command = "<Cmd>TourGuideNext<CR>" },
  { key = "prev_section", prompt = "TourGuide previous section keymap (empty to skip):", command = "<Cmd>TourGuidePrev<CR>" },
  { key = "next_topic", prompt = "TourGuide next topic keymap (empty to skip):", command = "<Cmd>TourGuideNextTopic<CR>" },
  { key = "prev_topic", prompt = "TourGuide previous topic keymap (empty to skip):", command = "<Cmd>TourGuidePrevTopic<CR>" },
}

local active = {}
local active_buffers = {}
local preferences = nil
local augroup = vim.api.nvim_create_augroup("tourguide_keymaps", { clear = true })

local function config_path()
  return vim.fn.stdpath("state") .. "/tourguide/keymaps.json"
end

local function read_preferences()
  local path = config_path()
  if vim.fn.filereadable(path) == 0 then return nil end

  local ok, decoded = pcall(vim.fn.json_decode, table.concat(vim.fn.readfile(path), "\n"))
  if ok and type(decoded) == "table" then return decoded end
  vim.notify("TourGuide could not read keymap preferences", vim.log.levels.WARN)
  return nil
end

local function write_preferences(preferences)
  local path = config_path()
  vim.fn.mkdir(vim.fn.fnamemodify(path, ":h"), "p")
  vim.fn.writefile(vim.split(vim.fn.json_encode(preferences), "\n", { plain = true }), path)
end

local function buffer_map(buf, lhs)
  for _, mapping in ipairs(vim.api.nvim_buf_get_keymap(buf, "n")) do
    if mapping.lhs == lhs then return mapping end
  end
end

local function prompt_preferences(done)
  local preferences = {}
  local index = 1

  local function prompt_next()
    local action = actions[index]
    if not action then
      write_preferences(preferences)
      done(preferences)
      return
    end

    vim.ui.input({ prompt = action.prompt }, function(value)
      preferences[action.key] = value or ""
      index = index + 1
      prompt_next()
    end)
  end

  prompt_next()
end

local function restore_map(lhs, previous, buf)
  if buf then
    pcall(vim.keymap.del, "n", lhs, { buffer = buf })
  else
    pcall(vim.keymap.del, "n", lhs)
  end
  if previous and previous.lhs and previous.lhs ~= "" then
    if buf then
      pcall(vim.api.nvim_buf_call, buf, function()
        vim.fn.mapset("n", true, previous)
      end)
    else
      pcall(vim.fn.mapset, "n", false, previous)
    end
  end
end

function M.restore()
  for _, mapping in ipairs(active) do
    restore_map(mapping.lhs, mapping.previous)
  end
  for buf, mappings in pairs(active_buffers) do
    if vim.api.nvim_buf_is_valid(buf) then
      for _, mapping in ipairs(mappings) do
        restore_map(mapping.lhs, mapping.previous, buf)
      end
    end
  end
  active = {}
  active_buffers = {}
  preferences = nil
  vim.api.nvim_clear_autocmds({ group = augroup })
end

local function apply_buffer_maps(buf)
  if not preferences or not vim.api.nvim_buf_is_valid(buf) then return end
  if vim.bo[buf].buftype ~= "" and vim.bo[buf].buftype ~= "nofile" then return end

  active_buffers[buf] = active_buffers[buf] or {}
  local tracked = {}
  for _, mapping in ipairs(active_buffers[buf]) do
    tracked[mapping.lhs] = mapping
  end

  for _, action in ipairs(actions) do
    local lhs = preferences[action.key]
    if type(lhs) == "string" and lhs ~= "" then
      local previous = tracked[lhs] and tracked[lhs].previous or buffer_map(buf, lhs)
      if not previous or not previous.lhs or previous.lhs == "" or previous.desc == "TourGuide " .. action.key:gsub("_", " ") then
        previous = nil
      end
      if not tracked[lhs] then table.insert(active_buffers[buf], { lhs = lhs, previous = previous }) end
      vim.keymap.set("n", lhs, action.command, {
        buffer = buf,
        silent = true,
        desc = "TourGuide " .. action.key:gsub("_", " "),
      })
    end
  end
end

local function apply_current_buffer_maps()
  apply_buffer_maps(vim.api.nvim_get_current_buf())
  vim.defer_fn(function()
    if state.tour then apply_buffer_maps(vim.api.nvim_get_current_buf()) end
  end, 100)
end

local function apply_preferences(next_preferences)
  M.restore()
  preferences = next_preferences

  for _, action in ipairs(actions) do
    local lhs = preferences[action.key]
    if type(lhs) == "string" and lhs ~= "" then
      local previous = vim.fn.maparg(lhs, "n", false, true)
      if not previous or not previous.lhs or previous.lhs == "" then previous = nil end
      table.insert(active, { lhs = lhs, previous = previous })
      vim.keymap.set("n", lhs, action.command, { silent = true, desc = "TourGuide " .. action.key:gsub("_", " ") })
    end
  end

  apply_current_buffer_maps()
  vim.api.nvim_create_autocmd({ "BufEnter", "FileType", "LspAttach" }, {
    group = augroup,
    callback = apply_current_buffer_maps,
  })
end

function M.activate()
  if not state.options.prompt_keymaps or #vim.api.nvim_list_uis() == 0 then
    M.restore()
    return
  end

  local preferences = read_preferences()
  if preferences then
    apply_preferences(preferences)
    return
  end

  prompt_preferences(apply_preferences)
end

return M

end

package.preload["tourguide.loader"] = function()
local M = {}

local function basename(path)
  return path:match("([^/]+)$") or path
end

local function is_step(node)
  return node.file or node.markdown or node.panes
end

local function flatten_node(node, breadcrumbs, out, depth)
  local next_breadcrumbs = vim.deepcopy(breadcrumbs)
  table.insert(next_breadcrumbs, node.title or "Untitled")

  if is_step(node) then
    node._breadcrumbs = next_breadcrumbs
    node._depth = depth
    node._label = node.title or node.file or "Untitled"
    node._kind = node.markdown and "markdown" or node.panes and "split" or "file"
    node._display_file = node.file and basename(node.file) or nil
    table.insert(out, node)
  end

  for _, child in ipairs(node.children or {}) do
    flatten_node(child, next_breadcrumbs, out, depth + 1)
  end
end

function M.flatten(tour)
  local out = {}
  for _, topic in ipairs(tour.topics or {}) do
    flatten_node(topic, {}, out, 0)
  end
  return out
end

function M.load(path_or_module)
  local ok, tour
  if path_or_module:match("%.lua$") or path_or_module:match("/") then
    ok, tour = pcall(dofile, path_or_module)
  else
    ok, tour = pcall(require, path_or_module)
  end
  if not ok then error(tour) end
  if type(tour) ~= "table" then error("tour must return a table") end
  if not tour.root then tour.root = vim.fn.getcwd() end
  local steps = M.flatten(tour)
  if #steps == 0 then error("tour has no steps") end
  return tour, steps
end

return M

end

package.preload["tourguide"] = function()
local loader = require("tourguide.loader")
local state = require("tourguide.state")
local nav = require("tourguide.navigation")
local sidebar = require("tourguide.sidebar")
local keymaps = require("tourguide.keymaps")

local M = {}

function M.start(path_or_module)
  local tour, steps = loader.load(path_or_module)
  keymaps.restore()
  state.reset()
  state.tour = tour
  state.steps = steps
  state.index = 1
  sidebar.render()
  state.windows = require("tourguide.layout").render(state.current_step(), state.tour, {})
  keymaps.activate()
end

function M.next() nav.next() end
function M.prev() nav.prev() end
function M.next_topic() nav.next_topic() end
function M.prev_topic() nav.prev_topic() end
function M.jump(index) nav.jump(index) end

function M.close()
  keymaps.restore()
  for _, step in ipairs(state.steps) do
    if step.file and state.tour then
      local path = (state.tour.root or vim.fn.getcwd()):gsub("/$", "") .. "/" .. step.file
      local buf = vim.fn.bufnr(path)
      if buf ~= -1 then vim.api.nvim_buf_clear_namespace(buf, state.ns, 0, -1) end
    end
  end
  state.reset()
end

function M.setup(opts)
  opts = opts or {}
  if opts.sidebar_width then state.sidebar.width = opts.sidebar_width end
  if opts.prompt_keymaps ~= nil then state.options.prompt_keymaps = opts.prompt_keymaps end

  vim.api.nvim_create_user_command("TourGuide", function(cmd) M.start(cmd.args) end, { nargs = 1, complete = "file" })
  vim.api.nvim_create_user_command("TourGuideNext", M.next, {})
  vim.api.nvim_create_user_command("TourGuidePrev", M.prev, {})
  vim.api.nvim_create_user_command("TourGuideNextTopic", M.next_topic, {})
  vim.api.nvim_create_user_command("TourGuidePrevTopic", M.prev_topic, {})
  vim.api.nvim_create_user_command("TourGuideJump", function(cmd) M.jump(tonumber(cmd.args)) end, { nargs = 1 })
  vim.api.nvim_create_user_command("TourGuideClose", M.close, {})
end

return M

end

vim.g.loaded_tourguide_nvim = 1
require("tourguide").setup()
