local modules = {
  { name = "tourguide.state", path = "lua/tourguide/state.lua" },
  { name = "tourguide.resolve", path = "lua/tourguide/resolve.lua" },
  { name = "tourguide.annotations", path = "lua/tourguide/annotations.lua" },
  { name = "tourguide.sidebar", path = "lua/tourguide/sidebar.lua" },
  { name = "tourguide.layout", path = "lua/tourguide/layout.lua" },
  { name = "tourguide.navigation", path = "lua/tourguide/navigation.lua" },
  { name = "tourguide.keymaps", path = "lua/tourguide/keymaps.lua" },
  { name = "tourguide.loader", path = "lua/tourguide/loader.lua" },
  { name = "tourguide", path = "lua/tourguide/init.lua" },
}

local output_path = "skills/tourguide/tourguide.lua"

local function read_file(path)
  local file, err = io.open(path, "rb")
  if not file then error(string.format("failed to read %s: %s", path, err)) end
  local content = file:read("*a")
  file:close()
  return content
end

local function write_file(path, content)
  local file, err = io.open(path, "wb")
  if not file then error(string.format("failed to write %s: %s", path, err)) end
  file:write(content)
  file:close()
end

local lines = {
  "-- Generated by scripts/bundle.lua. Do not edit manually.",
  "-- Run `make bundle` from the tourguide.nvim repository root to update.",
  "",
  "if vim.g.loaded_tourguide_nvim == 1 then",
  "  return",
  "end",
  "",
}

for _, module in ipairs(modules) do
  table.insert(lines, string.format("package.preload[%q] = function()", module.name))
  table.insert(lines, read_file(module.path))
  table.insert(lines, "end")
  table.insert(lines, "")
end

table.insert(lines, "vim.g.loaded_tourguide_nvim = 1")
table.insert(lines, "require(\"tourguide\").setup()")
table.insert(lines, "")

write_file(output_path, table.concat(lines, "\n"))
print(string.format("Wrote %s", output_path))
